//#define SECRET_SSID "Tele2_973609"
//#define SECRET_PASS "uzymzy5e"
//#define SECRET_SSID "Ludvigs iPhone"
//#define SECRET_PASS "luddepuddemedsinkudde"
//#define SECRET_SSID "Galaxy A12F785"
//#define SECRET_PASS "xuqj2217"
#define SECRET_SSID "ASUS_D8_2G"
#define SECRET_PASS "Pappirull1988"